In [1]:
height = float(input("enter height of the triangle:"))
base = float(input("enter the base of the triangle:"))

area = (1/2)*base*height
print("the area of the triangle is:", area)


enter height of the triangle: 45
enter the base of the triangle: 67.8


the area of the triangle is: 1525.5


In [3]:
print("hello world")

hello world


In [7]:
x = 13
y = 12
temp = x
print("the value of temp variable is",temp)
x = y
print("the value of x is",x)
y = temp
print("the value of y is",y)

the value of temp variable is 13
the value of x is 12
the value of y is 13


In [17]:
### num1 = float(input("enter a number"))
num2 = float(input("enter another number"))
num3 = float(input("enter last number"))
sum = num1 - num2 / num3
print("total sum of all three numbers is:",sum)

enter a number 34
enter another number 67.56
enter last number 6777


total sum of all three numbers is: 33.99003098716246


In [32]:
x = 12 
y = 13
x , y = y , x
print("the value of x is", x)
print("the value of y is", y)

the value of x is 13
the value of y is 12


In [40]:

num1 = int(input("enter a number here:"))
sr = num1**1/2
print("the squre root of the given number is:",sr)

enter a number here: 49


the squre root of the given number is: 24.5


In [48]:
import math
num = int(input("enter a number here:"))
sr = math.sqrt(num)
print("the squre root of the given number is",sr)

enter a number here: 89


the squre root of the given number is 9.433981132056603


In [46]:
km = float(input("enter your value in kilomitres:"))
miles = km*(0.6213710)
print(km,"kilometers in miles will be",miles ,"miles")

enter your value in kilomitres: 78888


78888.0 kilometers in miles will be 49018.715448 miles


In [60]:
num = float(input("enter a number here"))
if num > 0:
    print ('it is a positive number')
elif num == 0:
    print ('it is 0')
else:
    print('it is a negative number')


enter a number here -785.908


it is a negative number


In [68]:
num = float(input("enter your number"))
if num % 2 ==0:
    print("the number is even")
else:
    print("the number is odd")

enter your number 12


the number is even


In [70]:
year = int(input("enter a year"))
if (year % 400 ==0) and (year % 100 ==0):
    print(year,"is a leap year")
elif (year % 4 ==0) and (year % 100 !=0):
    print(year,"is a leap year")
else:
    print(year,"is not a leap year")

enter a year 2009


2009 is not a leap year


In [77]:
num1 = int(input("enter first number here"))
num2 = int(input("enter second number here"))
num3 = int(input("enter third number here"))
if (num1 > num2) and (num1 > num3):
    print(num1, "is the greatest number")
elif (num2 > num1) and (num2 > num3):
    print(num2,"is the greatest number")
else:
    print(num3,"is the greatest number")



enter first number here 45
enter second number here 87
enter third number here 90


90 is the greatest number


In [83]:
num = int(input("enter a number here:"))
if num == 1:
    print("it is not a prime number")
    if num > 1:
        for i in range (2,num):
            if num % i == 0:
                print("it is not a prime number")
                break
            else:
                print("it is a prime number")

enter a number here: 7


In [5]:
num = int(input("enter a number here"))
if num > 0:
    print("the number is positive")
elif num == 0:
    print("the number is zero")
else:
    print("the number is negative")

enter a number here -98


the number is negative


In [3]:
print ('hello world')

hello world


In [5]:
num = int(input("enter a number here"))
if num > 0:
    print("the number is positive")
elif num == 0:
    print("the number is zero")
else:
    print("the number is negative")

enter a number here 65


the number is positive


import random

user_choice = int(input("enter your choice:type 0 for rock, 1 for paper, 2 for scissors."))
if user_choice >= 3 or user_choice < 0:
    print ("invalid number, you lose")
else:
    computer_choice = random.randint(0, 2)
    print("computer chose:")
    print(computer_choice)
    if computer_choice == user_choice:
        print("it's a draw")
        
    elif computer_choice > user_choice:
        print("you lose")
    elif user_choice > computer_choice:
        print("you win")
    elif computer_choice == 0 and user_choice == 2:
        print("you lose")
    elif computer_choice == 2 and user_choice == 0:
        print("you win")


import random

user_choice = int(input("enter your choice:type 0 for rock, 1 for paper, 2 for scissors."))
if user_choice >= 3 or user_choice < 0:
    print ("invalid number, you lose")
else:
    computer_choice = random.randint(0, 2)
    print("computer chose:")
    print(computer_choice)
    if computer_choice == user_choice:
        print("it's a draw")
        
    elif computer_choice > user_choice:
        print("you lose")
    elif user_choice > computer_choice:
        print("you win")
    elif computer_choice == 0 and user_choice == 2:
        print("you lose")
    elif computer_choice == 2 and user_choice == 0:
        print("you win")


## import random

user_choice = int(input("enter your choice:type 0 for rock, 1 for paper, 2 for scissors."))
if user_choice >= 3 or user_choice < 0:
    print ("invalid number, you lose")
else:
    computer_choice = random.randint(0, 2)
    print("computer chose:")
    print(computer_choice)
    if computer_choice == user_choice:
        print("it's a draw")
    elif computer_choice == 0 and user_choice == 2:
        print("you lose")
    elif computer_choice == 2 and user_choice == 0:
        print("you win")
    elif computer_choice > user_choice:
        print("you lose")
    elif user_choice > computer_choice:
        print("you win")


In [ ]:
import numpy as np
my_list= [1,2,3]
print(type(my_list))
numpy_array = np.array

In [1]:
print('hello world')

hello world


In [3]:
num1 = int(input('Enter a number here'))
num2 = int(input('Enter another number here'))
sum = num1/num2
print(sum,"is the result of the equation")

Enter a number here 56
Enter another number here 7


8.0 is the result of the equation


In [5]:
import random
num = random.randint(0,199)
print(num)

194


In [1]:
import numpy as np

In [5]:
lst = [1, 2, 3, 4, 5]
print (lst)

[1, 2, 3, 4, 5]


In [7]:
print('1D Array')
b = np.array([[1, 2, 3, 4, 5],
              [6, 7, 7, 8, 9, ]])
print(b)

1D Array
[[1 2 3 4 5]
 [6 7 7 8 9]]


In [3]:
import numpy as np
print('3D Array')
c = np.array([[[1, 2, 3, 4, 5, 6,],
               [7, 8, 9, 10, 11, 12],
               [13,14,15,16,17,18]]])
print(c)

3D Array
[[[ 1  2  3  4  5  6]
  [ 7  8  9 10 11 12]
  [13 14 15 16 17 18]]]


In [13]:
import numpy as np
print ('2D Array')
c = np.array([[[[1.3, 3.4, 5, 6],
               [55.5, 6, 7, 8],
               [-44, -55, 5,5.6],
               [6,7,8,9]]]])
print(c)

2D Array
[[[[  1.3   3.4   5.    6. ]
   [ 55.5   6.    7.    8. ]
   [-44.  -55.    5.    5.6]
   [  6.    7.    8.    9. ]]]]


In [15]:
import random
user_choice = int(input('Enter a number here, 0 for rock, 1 for paper, 2 for scissors'))
if user_choice >=3 or user_choice < 0:
    print('invalid number')
else:
 computer_choice = random.randint(0,2)
print('computer chose',computer_choice)
if computer_choice == user_choice:
    print("It's a draw")
elif computer_choice == 0 and user_choice == 2:
    print("You win")
elif computer_choice == 2 and user_choice == 0:
    print("You lose")
elif computer_choice < user_choice:
    print("you win")
elif computer_choice > user_choice:
    print("you lose")

                  

Enter a number here, 0 for rock, 1 for paper, 2 for scissors 2


computer chose 0
You win


In [51]:
import random
user_choice = int(input('Enter a number here, 0 for rock, 1 for paper, 2 for scissors'))
if user_choice >=3 or user_choice < 0:
    print('invalid number')
else:
 computer_choice = random.randint(0,2)
print('computer chose',computer_choice)
if computer_choice == user_choice:
    print("It's a draw")
elif computer_choice == 0 and user_choice == 2:
    print("You win")
elif computer_choice == 2 and user_choice == 0:
    print("You lose")
elif computer_choice < user_choice:
    print("you win")
elif computer_choice > user_choice:
    print("you lose")

                  

Enter a number here, 0 for rock, 1 for paper, 2 for scissors 2


computer chose 0
You win


In [11]:
import numpy as np
print ('2d array')
a = np.array([[2,3,3,4,4,],
              [3,4,5,6,5]])
print(a)
print ('3d array')
b = np.array([[[2,2,2,3,4],
               [4,6,7,8,9,],
               [3,4,5,6,7]]])
print(b)
print(a.size)
print(b.size)
print(a.shape)
print(b.shape)
print(a.dtype)
print(b.dtype)
b.transpose()

2d array
[[2 3 3 4 4]
 [3 4 5 6 5]]
3d array
[[[2 2 2 3 4]
  [4 6 7 8 9]
  [3 4 5 6 7]]]
10
15
(2, 5)
(1, 3, 5)
int32
int32


array([[[2],
        [4],
        [3]],

       [[2],
        [6],
        [4]],

       [[2],
        [7],
        [5]],

       [[3],
        [8],
        [6]],

       [[4],
        [9],
        [7]]])

In [25]:
import numpy as np
np.ones((4,4),dtype = bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [55]:
import numpy as np
a = np. arange(2,20,2)
print(a)
a = a.reshape((3,3))
print (a)
a = a.flatten()
print(a)
a = a.ravel()
print (a)


[ 2  4  6  8 10 12 14 16 18]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[ 2  4  6  8 10 12 14 16 18]
[ 2  4  6  8 10 12 14 16 18]


In [77]:
import numpy as np
a = np. arange(1,51)
a = a. reshape(10,5)
print (a)
print (a[2:5])
print (a[2,2])
print (a[:,2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
13
[ 3  8 13 18 23 28 33 38 43 48]


In [13]:
np.random.random(1)

array([0.70709083])

In [15]:
np.random.rand(2,2)

array([[0.66380524, 0.17218785],
       [0.85313816, 0.97720188]])

In [17]:
np.random.randn(2,2)

array([[ 2.49805473,  1.51936046],
       [ 1.59091347, -0.29845624]])

In [19]:
a = np.arange(1,10)
np.random.choice(a)
print(a)

[1 2 3 4 5 6 7 8 9]


In [9]:
import pandas as pd
print(pd.__version__)

2.2.2


In [11]:
lst = [1,2,3,4,5,6,7]
print(lst)

[1, 2, 3, 4, 5, 6, 7]


In [17]:
series = pd.Series(lst)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64
<class 'pandas.core.series.Series'>


In [19]:
empty = pd.Series([])
empty

Series([], dtype: object)

In [23]:
a = pd.Series(['p','q','r','s','t',] , index = [10,11,12,13,14], name = 'ritu')
a

10    p
11    q
12    r
13    s
14    t
Name: ritu, dtype: object

In [27]:
scaler_series = pd.Series(0.5, index = [1,2,3,3])
scaler_series

1    0.5
2    0.5
3    0.5
3    0.5
dtype: float64

In [29]:
dict_series = pd.Series({'p':1, 'q':2, 'r':3, 's':4})
dict_series

p    1
q    2
r    3
s    4
dtype: int64

In [37]:
dict_series = pd.Series({'p':[1,2,3], 'q':[1,4,2], 'r':[4,6,3], 's':[8,8,4]})
dict_series

p    [1, 2, 3]
q    [1, 4, 2]
r    [4, 6, 3]
s    [8, 8, 4]
dtype: object

In [31]:
dict_series[0]

C:\Users\user\AppData\Local\Temp\ipykernel_13588\1198263229.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  dict_series[0]


1

In [33]:
dict_series[0:3]

p    1
q    2
r    3
dtype: int64

In [35]:
max(dict_series)

4

In [39]:
import pandas as pd
df = pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [41]:
lst = [1,2,3,4,5,6,7]
df = pd.DataFrame(lst)
df

0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [43]:
lst = [[1,2,3,4,5],[11,12,13,14,15]]
df = pd.DataFrame(lst)
df

0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15

In [45]:
a = [{'a':5,'b':7,'c':8,'d':2},
     {'a':2,'b':3,'c':6,'d':11}]
df = pd.DataFrame(a)
df

a  b  c   d
0  5  7  8   2
1  2  3  6  11

In [47]:
b = {'Roll number':pd.Series([1,2,3,4,5]),
     'math':pd.Series([78,98,99,88,90]),
     'physics':pd.Series([99,98,78,88,90])}
df = pd.DataFrame(b)
df

Roll number  math  physics
0            1    78       99
1            2    98       98
2            3    99       78
3            4    88       88
4            5    90       90

In [15]:
import pandas as pd
df = pd.read_csv(r'C:\Users\user\Downloads\archive (1).zip')
df.head()



gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard   
1  female        group C                some college      standard   
2  female        group B             master's degree      standard   
3    male        group A          associate's degree  free/reduced   
4    male        group C                some college      standard   

  test preparation course  math score  reading score  writing score  
0                    none          72             72             74  
1               completed          69             90             88  
2                    none          90             95             93  
3                    none          47             57             44  
4                    none          76             78             75

In [29]:
df.loc[3]

gender                                       male
race/ethnicity                            group A
parental level of education    associate's degree
lunch                                free/reduced
test preparation course                      none
math score                                     47
reading score                                  57
writing score                                  44
Name: 3, dtype: object

In [35]:
df.loc[3,'reading score']

57

In [37]:
df.loc[5:15, 'reading score']

5     83
6     95
7     43
8     64
9     60
10    54
11    52
12    81
13    72
14    53
15    75
Name: reading score, dtype: int64

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64 
 6   reading score                1000 non-null   int64 
 7   writing score                1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB


In [43]:
df.describe()

math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000